// **************************************************************
// Purpose: Write XYZ files 
//
// 2003-2012, Roberto Flores-Moreno
// **************************************************************

#include <fstream>
#include <iomanip>

#include <fcns.h>
#include <global.h>

using namespace std;

void writexyz(const char* filename)
{

  ofstream fout(filename);
  if ( fout.fail() )
  {
    errmsg(__FILE__,__LINE__,"Error opening file",0);
  };

  int i,iatom,ndummy;

  ndummy = 0;
  for ( iatom = 0 ; iatom < NATOM ; iatom++ )
  {
    if (ATOMNO[iatom]==0) ndummy++;
  }

  fout << NATOM-ndummy << "\n";
  fout << "Geometry in Angstroms generated by "<<PROGRAM_NAME<<endl;
  for ( iatom = 0 ; iatom < NATOM ; iatom++ )
  {
    if (ATOMNO[iatom]!=0) 
    {
      fout << setw(2) << left << ELEMENT_SYMBOL[ATOMNO[iatom]] << " ";
      for ( i = 0 ; i < 3 ; i++ )
      {
        fout << fixed << setw(10) << setprecision(5) << right 
             << BohrToAngstrom(COORD[1][iatom][i]) << " ";
      }
      fout << "\n";
    }
  }
  fout << "\n";

  fout.close();
};
